# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptc_deco/api/api_gql/queries/proto/advertising_side.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ptc_deco/api/api_gql/queries/proto/advertising_side.proto',
  package='advertising_sides',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9ptc_deco/api/api_gql/queries/proto/advertising_side.proto\x12\x11\x61\x64vertising_sides\"\xe2\x03\n\x0bReservation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdate_from\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61te_to\x18\x03 \x01(\t\x12\x1e\n\x16reservation_type_title\x18\x04 \x01(\t\x12\x1b\n\x13reservation_type_id\x18\x05 \x01(\t\x12\x15\n\rproject_title\x18\x06 \x01(\t\x12 \n\x18sales_manager_first_name\x18\x07 \x01(\t\x12\x1f\n\x17sales_manager_last_name\x18\x08 \x01(\t\x12&\n\x1e\x62\x61\x63k_office_manager_first_name\x18\t \x01(\t\x12%\n\x1d\x62\x61\x63k_office_manager_last_name\x18\n \x01(\t\x12\x13\n\x0b\x62rand_title\x18\x0b \x01(\t\x12\x14\n\x0cproject_code\x18\x0c \x01(\t\x12\x1a\n\x12project_start_date\x18\r \x01(\t\x12\x1b\n\x13project_num_in_year\x18\x0e \x01(\x05\x12\x12\n\nproject_id\x18\x0f \x01(\t\x12\x17\n\x0fproject_comment\x18\x10 \x01(\t\x12\x10\n\x08\x62randing\x18\x11 \x01(\x08\x12\x1a\n\x12project_created_at\x18\x12 \x01(\t\"\xd7\x03\n\x10\x43onstructionSide\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x15\x61\x64vertising_side_code\x18\x02 \x01(\t\x12\x11\n\tside_code\x18\x03 \x01(\t\x12\x13\n\x0b\x66ormat_code\x18\x04 \x01(\t\x12\x14\n\x0c\x66ormat_title\x18\x05 \x01(\t\x12\x19\n\x11status_connection\x18\x06 \x01(\x08\x12\x17\n\x0fnum_in_district\x18\x07 \x01(\x05\x12\x16\n\x0epostcode_title\x18\x08 \x01(\t\x12\x12\n\ncity_title\x18\t \x01(\t\x12\x34\n\x0creservations\x18\n \x03(\x0b\x32\x1e.advertising_sides.Reservation\x12\x0f\n\x07package\x18\x0b \x01(\t\x12\x16\n\x0e\x64istrict_title\x18\x0c \x01(\t\x12\x1e\n\x16\x61\x64vertising_side_title\x18\r \x01(\t\x12\x0c\n\x04size\x18\x0e \x01(\t\x12\x12\n\nside_title\x18\x0f \x01(\t\x12\x13\n\x0bowner_title\x18\x10 \x01(\t\x12\x12\n\nis_non_rts\x18\x11 \x01(\x08\x12\x19\n\x11marketing_address\x18\x12 \x01(\t\x12\x15\n\rlegal_address\x18\x13 \x01(\t\"S\n\x11\x43onstructionSides\x12>\n\x11\x63onstruction_side\x18\x01 \x03(\x0b\x32#.advertising_sides.ConstructionSideb\x06proto3'
)




_RESERVATION = _descriptor.Descriptor(
  name='Reservation',
  full_name='advertising_sides.Reservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='advertising_sides.Reservation.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_from', full_name='advertising_sides.Reservation.date_from', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_to', full_name='advertising_sides.Reservation.date_to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reservation_type_title', full_name='advertising_sides.Reservation.reservation_type_title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reservation_type_id', full_name='advertising_sides.Reservation.reservation_type_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_title', full_name='advertising_sides.Reservation.project_title', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sales_manager_first_name', full_name='advertising_sides.Reservation.sales_manager_first_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sales_manager_last_name', full_name='advertising_sides.Reservation.sales_manager_last_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='back_office_manager_first_name', full_name='advertising_sides.Reservation.back_office_manager_first_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='back_office_manager_last_name', full_name='advertising_sides.Reservation.back_office_manager_last_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand_title', full_name='advertising_sides.Reservation.brand_title', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_code', full_name='advertising_sides.Reservation.project_code', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_start_date', full_name='advertising_sides.Reservation.project_start_date', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_num_in_year', full_name='advertising_sides.Reservation.project_num_in_year', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='advertising_sides.Reservation.project_id', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_comment', full_name='advertising_sides.Reservation.project_comment', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branding', full_name='advertising_sides.Reservation.branding', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_created_at', full_name='advertising_sides.Reservation.project_created_at', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=563,
)


_CONSTRUCTIONSIDE = _descriptor.Descriptor(
  name='ConstructionSide',
  full_name='advertising_sides.ConstructionSide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='advertising_sides.ConstructionSide.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advertising_side_code', full_name='advertising_sides.ConstructionSide.advertising_side_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side_code', full_name='advertising_sides.ConstructionSide.side_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format_code', full_name='advertising_sides.ConstructionSide.format_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format_title', full_name='advertising_sides.ConstructionSide.format_title', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_connection', full_name='advertising_sides.ConstructionSide.status_connection', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_in_district', full_name='advertising_sides.ConstructionSide.num_in_district', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='postcode_title', full_name='advertising_sides.ConstructionSide.postcode_title', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city_title', full_name='advertising_sides.ConstructionSide.city_title', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reservations', full_name='advertising_sides.ConstructionSide.reservations', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package', full_name='advertising_sides.ConstructionSide.package', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='district_title', full_name='advertising_sides.ConstructionSide.district_title', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advertising_side_title', full_name='advertising_sides.ConstructionSide.advertising_side_title', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='advertising_sides.ConstructionSide.size', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side_title', full_name='advertising_sides.ConstructionSide.side_title', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_title', full_name='advertising_sides.ConstructionSide.owner_title', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_non_rts', full_name='advertising_sides.ConstructionSide.is_non_rts', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marketing_address', full_name='advertising_sides.ConstructionSide.marketing_address', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='legal_address', full_name='advertising_sides.ConstructionSide.legal_address', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=1037,
)


_CONSTRUCTIONSIDES = _descriptor.Descriptor(
  name='ConstructionSides',
  full_name='advertising_sides.ConstructionSides',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='construction_side', full_name='advertising_sides.ConstructionSides.construction_side', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1039,
  serialized_end=1122,
)

_CONSTRUCTIONSIDE.fields_by_name['reservations'].message_type = _RESERVATION
_CONSTRUCTIONSIDES.fields_by_name['construction_side'].message_type = _CONSTRUCTIONSIDE
DESCRIPTOR.message_types_by_name['Reservation'] = _RESERVATION
DESCRIPTOR.message_types_by_name['ConstructionSide'] = _CONSTRUCTIONSIDE
DESCRIPTOR.message_types_by_name['ConstructionSides'] = _CONSTRUCTIONSIDES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reservation = _reflection.GeneratedProtocolMessageType('Reservation', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATION,
  '__module__' : 'ptc_deco.api.api_gql.queries.proto.advertising_side_pb2'
  # @@protoc_insertion_point(class_scope:advertising_sides.Reservation)
  })
_sym_db.RegisterMessage(Reservation)

ConstructionSide = _reflection.GeneratedProtocolMessageType('ConstructionSide', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRUCTIONSIDE,
  '__module__' : 'ptc_deco.api.api_gql.queries.proto.advertising_side_pb2'
  # @@protoc_insertion_point(class_scope:advertising_sides.ConstructionSide)
  })
_sym_db.RegisterMessage(ConstructionSide)

ConstructionSides = _reflection.GeneratedProtocolMessageType('ConstructionSides', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRUCTIONSIDES,
  '__module__' : 'ptc_deco.api.api_gql.queries.proto.advertising_side_pb2'
  # @@protoc_insertion_point(class_scope:advertising_sides.ConstructionSides)
  })
_sym_db.RegisterMessage(ConstructionSides)


# @@protoc_insertion_point(module_scope)
