#ifndef PROJECT_OPTIMIZATION
#define PROJECT_OPTIMIZATION

#if defined __clang__
  #define COMPILER_PUSH_O1
  #define COMPILER_PUSH_O2
  #define COMPILER_PUSH_O3
  #define COMPILER_POP
#elif defined __GNUC__
  #define COMPILER_PUSH_O1  _Pragma("GCC push_options") _Pragma ("GCC optimize (\"-O1\")")
  #define COMPILER_PUSH_O2  _Pragma("GCC push_options") _Pragma ("GCC optimize (\"-O2\")")
  #define COMPILER_PUSH_O3  _Pragma("GCC push_options") _Pragma ("GCC optimize (\"-O3\")")
  #define COMPILER_POP      _Pragma("GCC pop_options")
#else
  #define COMPILER_PUSH_O1
  #define COMPILER_PUSH_O2
  #define COMPILER_PUSH_O3
  #define COMPILER_POP
#endif


#ifndef GLOBAL_PARSER_DEBUG
  #define COMPILER_LEXER_OPTIMIZATION_PUSH()       COMPILER_PUSH_O2
  #define COMPILER_LEXER_OPTIMIZATION_POP()        COMPILER_POP

  #ifdef PARSER_O3_ENABLE
    #define COMPILER_BISON_OPTIMIZATION_PUSH()       COMPILER_PUSH_O3
    #define COMPILER_BISON_OPTIMIZATION_POP()        COMPILER_POP
  #else
    #define COMPILER_BISON_OPTIMIZATION_PUSH()
    #define COMPILER_BISON_OPTIMIZATION_POP()
  #endif

  #define COMPILER_LOCATIONS_OPTIMIZATATION_PUSH() COMPILER_PUSH_O2
  #define COMPILER_LOCATIONS_OPTIMIZATATION_POP()  COMPILER_POP

  #define COMPILER_HASH_FUN_OPTIMIZATION_PUSH()    COMPILER_PUSH_O3
  #define COMPILER_HASH_FUN_OPTIMIZATION_POP()     COMPILER_POP

  #define COMPILER_SITER_OPTIMIZATION_PUSH()       COMPILER_PUSH_O3
  #define COMPILER_SITER_OPTIMIZATION_POP()        COMPILER_POP

  #define COMPILER_SMARTPTR_OPTIMIZATION_PUSH()    COMPILER_PUSH_O3
  #define COMPILER_SMARTPTR_OPTIMIZATION_POP()     COMPILER_POP

#else
  #define COMPILER_LEXER_OPTIMIZATION_PUSH()
  #define COMPILER_LEXER_OPTIMIZATION_POP()

  #define COMPILER_BISON_OPTIMIZATION_PUSH()
  #define COMPILER_BISON_OPTIMIZATION_POP()

  #define COMPILER_LOCATIONS_OPTIMIZATATION_PUSH()
  #define COMPILER_LOCATIONS_OPTIMIZATATION_POP()

  #define COMPILER_HASH_FUN_OPTIMIZATION_PUSH()
  #define COMPILER_HASH_FUN_OPTIMIZATION_POP()

  #define COMPILER_SITER_OPTIMIZATION_PUSH()
  #define COMPILER_SITER_OPTIMIZATION_POP()

  #define COMPILER_SMARTPTR_OPTIMIZATION_PUSH()
  #define COMPILER_SMARTPTR_OPTIMIZATION_POP()
#endif

//#define SMARTPTR_DEBUG1 1






#endif // PROJECT_OPTIMIZATION
